### ISSUE TITLE
Linking hdf5 files

### ISSUE THREAD

**Issue by icoert** [jupyterlab/jupyterlab-hdf5#74] opened 2021-01-25 12:50 UTC
Hi there, 

It seems there might be a strange behavior when using external link with different hdf5 files.

In the below example the linked file doesn't reach the expectations.

```
import h5py
import numpy as np
 
with h5py.File('atomicfile.hdf5', 'a') as f:
    dataset = np.random.rand(100)
    f.create_dataset('testset', data=dataset)
 
with h5py.File('linkfile.hdf5', 'a') as f:
    f['atomicfile'] = h5py.ExternalLink('atomicfile.hdf5', '/')
```

Anyway, this is the workaround which seems to solve the problem.

```
import h5py
import numpy as np

with h5py.File('atomicfile.hdf5', 'w') as f:
    dataset = np.random.rand(100)
    f.create_dataset('testset', data=dataset)

with h5py.File('linkfile.hdf5', 'w') as f:
    f['/testset'] = h5py.ExternalLink('atomicfile.hdf5', '/testset')
    
with h5py.File('linkfile.hdf5', 'r') as f:
    keys = list(f.keys())
    print(keys[0])
```
Or the following case  using a group.

```
import h5py
import numpy as np

with h5py.File('atomicfile.hdf5', 'w') as f:
    dataset = np.random.rand(100)
    g = f.create_group('test')
    g.create_dataset('testset', data=dataset)

with h5py.File('linkfile.hdf5', 'w') as f:
    f['/test'] = h5py.ExternalLink('atomicfile.hdf5', '/test')
    
with h5py.File('linkfile.hdf5', 'r') as f:
    keys = list(f.keys())
    print(keys[0])
```

Opinions?

**Comment by loichuder** [comment] 2021-01-25 14:06
If I understand correctly, you can only resolve the external link if the name of the external link matches the name of the group/dataset it links to ?

**Comment by icoert** [comment] 2021-01-25 14:10
> If I understand correctly, you can only resolve the external link if the name of the external link matches the name of the group/dataset it links to ?

Yes, indeed.

**Comment by loichuder** [comment] 2021-01-25 14:22
After a quick look in the code, `ExternalLinks` are indeed not yet supported. The fact that you can resolve them by using the same case is an edge case and even so, I am not convinced it works fully.

Some work is needed to handle the cases where the data comes from different files.

**Comment by telamonian** [comment] 2021-01-28 17:03
I cannot reproduce @icoert's original issue. The following code

```python
with h5py.File('atomicfile.hdf5', 'w') as f:
    dataset = np.random.rand(100)
    f.create_dataset('testset', data=dataset)

with h5py.File('linkfile.hdf5', 'w') as f:
    f['foo'] = h5py.ExternalLink('atomicfile.hdf5', '/')
    print(f['foo/testset'])
```

prints out

```
<HDF5 dataset "testset": shape (100,), type "<f8">
```

which is exactly what you'd expect.

In any case, this seems more an issue for `h5py` than like an issue we should be dealing with in this PR. @icoert Were you having trouble with the Jupyterlab extension `jupyterlab_hdf5`, or was the issue just with the example `h5py` code that you posted?

**Comment by icoert** [comment] 2021-02-04 09:32
> In any case, this seems more an issue for h5py than like an issue we should be dealing with in this PR. @icoert Were you having trouble with the Jupyterlab extension jupyterlab_hdf5, or was the issue just with the example h5py code that you posted?

@telamonian, I am encountering the problem inside the viwer, it seems it's not related to `h5py`.

**Comment by loichuder** [comment] 2021-09-06 13:08
v0.7.0 now explicitly handles external and soft links. 

Clicking on a link allows see to where it points but **does not resolve it for now**.

**Comment by loichuder** [comment] 2021-09-23 11:52
v0.8.0 adds a setting to enable link resolution. Closing this then.

**Closed by loichuder** 2021-09-23 11:52 UTC
