### ISSUE TITLE
Failure to open a 1D dataset

### ISSUE THREAD

**Issue by jchia** [jupyterlab/jupyterlab-hdf5#23] opened 2019-12-02 02:16 UTC
With the HDF5 file created by the following code, jupyterlab-hdf 0.1.0 fails to open the `x` dataset, which is 1D, showing no data. With the `y` and `z` datasets, which are 2D and 3D respectively, there is no problem.

Maybe there's a bug where the extension forgets that datasets can be one-dimensional.

```#!/usr/bin/env python
import h5py
import numpy as np


x = np.zeros(shape=(1,), dtype=np.float64)
y = np.zeros(shape=(1, 1), dtype=np.float64)
z = np.zeros(shape=(1, 1, 1), dtype=np.float64)
with h5py.File('/tmp/bad.hdf5', 'w') as f:
    f.create_dataset('x', data=x)
    f.create_dataset('y', data=y)
    f.create_dataset('z', data=z)
```

**Comment by telamonian** [comment] 2019-12-02 06:46
Duplicate of #18. Currently only 2D datasets are supported. This will get fixed in the next release as part of the upgrade to handle general nD datasets.

**Comment by telamonian** [comment] 2020-10-12 16:57
I'm closing this to consolidate further discussion to #18

**Closed by telamonian** 2020-10-12 16:57 UTC
Labels: tag:Duplicate
